branches:
  except:
    - circleci
    - travisci
    - gh-pages
    - build_linux_64
    - build_osx_64

environment:
  matrix:
    - COMPILER: mingw
      PLATFORM: Win32

    #- COMPILER: mingw-w64
      #GENERATOR: MinGW Makefiles
      #PLATFORM: Win64

    - COMPILER: msvc
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: Win32

    - COMPILER: msvc
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      PLATFORM: Win64

build_script:
  - ps: $Env:BUILD_DIR = "build"
  - ps: tools/ci/build.ps1
