version: 2

general:
  branches:
    ignore:
      - appveyor
      - travisci
      - gh-pages
      - build_linux_64
      - build_osx_64

jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: pushd tools/ci && ./install_deps.sh && popd
      - run:
          name: Compiling Code
          command: pushd tools/ci && BUILD_DIR=build CMAKE_FLAGS="-DTINYSPLINE_ENABLE_PYTHON=TRUE" ./compile.sh && popd
